"""게임 전역 상수 및 설정값."""

from __future__ import annotations

# ── 화면 설정 ──
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
TITLE = "MotionMagic - Battle Skeleton"

# ── 타일맵 ──
TILE_SIZE = 64

# ── 전장 ──
NUM_FIELDS = 2
BASE_LINE_X = 45
PLAYER_X = 95
PLAYER_Y = SCREEN_HEIGHT // 2


# ── 전투 배경 ──
BATTLE_BACKGROUND_FILES = (
    "assets/maps/ice_battle.png",
    "assets/maps/fire_battle.png",
)

# ── 개발용 제스처 입력 ──
# 실제 제스처 모듈 연결 전까지 q/w/e를 가위/바위/보로 사용한다.
GESTURE_SCISSORS = "scissors"
GESTURE_ROCK = "rock"
GESTURE_PAPER = "paper"
GESTURE_LABELS: list[str] = [GESTURE_SCISSORS, GESTURE_ROCK, GESTURE_PAPER]
GESTURE_COMBO_SIZE = 3
GESTURE_CONFIDENCE_THRESHOLD = 0.85

# ── AI 모델 ──
NUM_LANDMARKS = 21
NUM_COORDS = 3
NUM_FINGER_FEATURES = 5
INPUT_DIM = NUM_LANDMARKS * NUM_COORDS + NUM_FINGER_FEATURES
NUM_GESTURE_CLASSES = len(GESTURE_LABELS)

# ── 전투 ──
MAX_ENEMIES_PER_WAVE = 20
AUTO_ATTACK_RANGE = 0  # 자동조준 평타 삭제: 0으로 비활성화
AUTO_ATTACK_COOLDOWN_MS = 0
MANA_CHARGE_PER_SECOND = 28.0
WAVE_CLEAR_DELAY = 1.5

# ── 에임 ──
AIM_SENSITIVITY = 2.5
AIM_EMA_ALPHA = 0.3
AIM_BUFFER_SIZE = 5

# ── 색상 ──
COLOR_BG = (15, 15, 25)
COLOR_FIELD_BG = (24, 28, 42)
COLOR_INACTIVE_FIELD_BG = (12, 13, 20)
COLOR_WHITE = (255, 255, 255)
COLOR_MUTED = (160, 166, 185)
COLOR_HUD_HP = (76, 209, 55)
COLOR_HUD_MP = (72, 126, 255)
COLOR_BASE = (239, 196, 15)
COLOR_ENEMY = (235, 87, 87)
COLOR_ENEMY_FAST = (255, 120, 90)
COLOR_ENEMY_TANK = (170, 80, 70)
COLOR_PROJECTILE = (116, 185, 255)
COLOR_EXPLOSION = (255, 177, 66)
COLOR_LIGHTNING = (120, 210, 255)
COLOR_STUN = (241, 196, 15)
